site_self_storage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from storage.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('storage.urls', 'storage'), namespace='storage')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path("select2/", include("django_select2.urls")),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.login_view,    name='login'),
    path('logout/', views.logout_view,  name='logout'),
    path('profile/update/', views.profile_update, name='profile_update'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class CustomUser(AbstractUser):
    phone = PhoneNumberField(
        verbose_name='Мобильный номер',
        region='RU',
        unique=True
    )
    address = models.CharField(
        'Адрес',
        max_length=250
    )
    photo = models.ImageField(
        'Фото',
        upload_to='photos/',
        default='photos/unnamed.jpg',
        blank=True,
        null=True
    )
    email = models.EmailField(
        'Почта',
        unique=True
    )

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.phone}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = (
            'first_name',
            'last_name',
            'email',
            'phone',
            'address',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data['email']
        if commit:
            user.save()
        return user

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from users.forms import CustomUserCreationForm
from users.models import CustomUser


def register_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('storage:lk')
    else:
        form = CustomUserCreationForm()
    return render(
        request,
        'register.html',
        {'form': form}
    )


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('storage:lk')
        else:
            messages.error(request, 'Неверный логин или пароль')
    else:
        form = AuthenticationForm()

    return render(
        request,
        'login.html',
        {'form': form}
    )


@login_required
def logout_view(request):
    logout(request)
    return redirect('storage:index')


@login_required
def profile_update(request):
    if request.method == 'POST':
        user = request.user
        username = request.POST.get('username')
        phone = request.POST.get('phone')
        password = request.POST.get('password')

        updated_fields = []

        if username and username != user.username:
            user.username = username
            updated_fields.append('E-mail')

        if phone and phone != user.phone:
            user.phone = phone
            updated_fields.append('Телефон')

        if password:
            user.set_password(password)
            update_session_auth_hash(request, user)
            updated_fields.append('Пароль')

        user.save()

        if updated_fields:
            messages.success(request, f"Обновлены: {', '.join(updated_fields)}.")
        else:
            messages.info(request, 'Изменений не было.')

        return redirect('storage:lk')

    return redirect('storage:lk')

templates/boxes.html
{% extends "base.html" %}
{% load static %}
{% block title %}Тарифы{% endblock %}
{% block content %}
    <main class="container mt-header">
        {% include "includes/top-banner.html" %}
        {% include "includes/box_rental_list.html" %}
        {% include "includes/storage-card-full.html" %}
    </main>
{% endblock %}

templates/includes/entrance-exit.html
{% if user.is_authenticated %}
    <a class="{{ style }}" href="{% url 'users:logout' %}">Выйти</a>
{% else %}
  <a class="{{ style }}" href="{% url 'users:login' %}">Войти</a>
{% endif %}

templates/includes/navbar.html
{% load static %}
<header class="navbar navbar-expand-xl navbar-light fixed-top bg-white py-5">
	<nav class="container">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="{% url 'storage:index' %}">
			<img src="{% static 'img/Vector.svg' %}" alt="[]">
			<img src="{% static 'img/SelfStorage.svg' %}" alt="SelfStorage">
		</a>
		<div class="collapse navbar-collapse justify-content-end" id="navbar">
			<ul class="navbar-nav">
				<li class="nav-item me-5">
					<a class="nav-link SelfStorage_black" href="{% url 'storage:boxes' %}">Рассчитать стоимость</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link SelfStorage_black" href="{% url 'storage:faq' %}">Правила хранения</a>
				</li>
				<li class="nav-item me-5">
                    {% if user.is_authenticated %}
					<a class="nav-link SelfStorage_black" href="{% url 'storage:create_order' %}" data-toggle="modal" data-target="#orderModal">Арендовать бокс</a>
                    {% else %}
                    <a class="nav-link SelfStorage_black" href="{% url 'users:login' %}">Арендовать бокс</a>
                    {% endif %}
				</li>
                     <li class="nav-item me-5">
                         {% include "includes/entrance-exit.html" with style="nav-link SelfStorage_green" %}
                     </li>
				<li class="nav-item d-flex align-items-center">
					<div class="d-flex justify-content-center align-items-center rounded-pill SelfStorage__bg_green me-2" style="height: 36px; width: 36px;">
						<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="white" class="bi bi-telephone-fill" viewBox="0 0 16 16">
							<path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
						</svg>
					</div>
					<b>8 (800) 000-00-00</b>
				</li>
			</ul>
		</div>
	</nav>
</header>
{% include "includes/order_create.html" %}

templates/includes/top-banner.html
{% load static %}
<article class="row">
    <div class="col-12 col-lg-6 mb-3 mb-lg-0">
        <h1 class="fw-bold SelfStorage_green mb-5">Доставка и бережное хранение ваших вещей</h1>
        <h4 class="fw-lighter SelfStorage_grey mb-5">Аренда бокса на любой срок Бесплатная доставка от вашего дома </h4>
        <form class="">
            <input type="text" required name="EMAIL1" class="form-control border-8 mb-4 py-3 px-5 border-0 fs_24 SelfStorage__bg_lightgrey" placeholder="Укажите ваш e-mail">
            {% if user.is_authenticated %}
                <a href="{% url 'storage:create_order' %}" class="btn border-8 py-3 px-5 w-100 text-white fs_24 SelfStorage__bg_orange SelfStorage__btn2_orange" data-toggle="modal" data-target="#orderModal">Арендовать бокс</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="btn border-8 py-3 px-5 w-100 text-white fs_24 SelfStorage__bg_orange SelfStorage__btn2_orange">Арендовать бокс</a>
            {% endif %}
            <span class="text-center fw-light">Нажимая на кнопку, вы подтверждаете свое <a href="{% static 'Consent to the processing of personal data.pdf' %}" class="link-dark">согласие на обработку персональных данных</a></span>
        </form>
    </div>
    <div class="col-12 col-lg-6 SelfStorage__img"></div>
</article>

templates/includes/video-banner.html
{% load static %}
<article class="row pt-header">
    <h1 class="text-center fw-bold SelfStorage_green mb-4">Узнайте, как работает SelfStorage всего за минуту</h1>
    <div class="d-flex justify-content-center">
        <iframe class="w-100" height="700" src="https://www.youtube.com/embed/NsSC4pQ6HJE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
</article>

templates/lk.html
{% extends "base.html" %}
{% load static %}
{% block title %}Личный кабинет{% endblock %}
{% block content %}

{% if user.is_authenticated %}
    <main class="container mt-header ">
        <div class="row" role="tablist">
            {% include "includes/small-menu.html" %}
            <div class="col-lg-9">
                <div class="card tab-content p-5">
                    <div class="tab-pane fade show active" id="LK" role="tabpanel" aria-labelledby="LK-tab">
                        <div class="row">
                            <div class="col-12 col-sm-5 d-flex flex-column align-items-center">
                                <img src="{{ user.photo.url }}" class="rounded-pill mb-3" alt="">
                                <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                            </div>
                            <div class="col-12 col-sm-7 d-flex flex-column">
                                <form method="post" action="{% url 'users:profile_update' %}">
                                    {% csrf_token %}
                                    <label class="fs_24 SelfStorage_green ms-2" for="EMAIL">E-mail</label>
                                    <input type="email" name="username" id="EMAIL" class="form-control fs_24 ps-2 SelfStorage__input" value="{{ user.username }}" disabled>

                                    <label class="fs_24 SelfStorage_green ms-2" for="PHONE">Телефон</label>
                                    <input type="tel" name="phone" id="PHONE" class="form-control fs_24 ps-2 SelfStorage__input" value="{{ user.phone }}" disabled>

                                    <label class="fs_24 SelfStorage_green ms-2" for="PASSWORD">Пароль</label>
                                    <input type="password" name="password" id="PASSWORD" class="form-control fs_24 ps-2 SelfStorage__input" value="********" placeholder="Введите новый пароль" disabled>

                                    <button type="submit" class="btn SelfStorage_green ps-1" id="save" style="display: none">Сохранить</button>
                                    <a class="btn SelfStorage_orange ps-1" id="edit">Редактировать</a>

                                    <script>
                                        document.getElementById('edit').addEventListener('click', e => {
                                            e.preventDefault()
                                            document.getElementById('EMAIL').disabled = false
                                            document.getElementById('PHONE').disabled = false
                                            document.getElementById('PASSWORD').disabled = false
                                            document.getElementById('PASSWORD').type = 'text'
                                            document.getElementById('PASSWORD').value = '';
                                            document.getElementById('edit').style.display = 'none'
                                            document.getElementById('save').style.display = 'inline-block'
                                        })
                                        document.getElementById('save').addEventListener('click', () => {
                                            setTimeout(() => {
                                                document.getElementById('EMAIL').disabled = true
                                                document.getElementById('PHONE').disabled = true
                                                document.getElementById('PASSWORD').disabled = true
                                                document.getElementById('PASSWORD').type = 'password'
                                                document.getElementById('edit').style.display = 'inline-block'
                                                document.getElementById('save').style.display = 'none'
                                            }, 0)
                                        })
                                    </script>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% else %}
    <main class="container mt-header">
        <div class="row top-up butt-up" role="tablist">
            <span class="fs_24 ">Войдите в учетную запись
                <a class="fs_24 SelfStorage_orange" href=
                        "{% url 'users:login' %}">войти</a>,
                 или
                 <a class=" fs_24 SelfStorage_orange" href=
                         "{% url 'users:login' %}">зарегистрируйтесь</a>.
            </span>
        </div>
    </main>
{% endif %}
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}Войти{% endblock %}
{% block content %}
    <div class="top-up pt-5 d-flex justify-content-center align-items-center">
        <form method="POST" action="{% url 'users:login' %}" class="d-flex flex-column align-items-center"
              style="max-width: 420px">
            {% csrf_token %}
            <h1 class="modal-title text-center fw-bold mb-3">Вход</h1>

            {% for message in messages %}
              <div class="alert alert-danger w-100 text-center">{{ message }}</div>
            {% endfor %}
            {{ form.non_field_errors }}

            <input type="email" required name="username"
                   class="form-control border-8 mb-3 py-3 px-5 border-0
                   fs_20 SelfStorage__bg_lightgrey"
                   placeholder="E-mail">

            <input type="password" required name="password"
                   class="form-control border-8 mb-3 py-3 px-5 border-0
                   fs_20 SelfStorage__bg_lightgrey"
                   placeholder="Пароль">

            <button type="submit"
                    class="btn border-8 py-3 px-5 mt-5 mb-3 w-100 text-white fs_24 SelfStorage__bg_orange SelfStorage__btn2_orange">
                Войти
            </button>

            <span>Нет аккаунта?
                <a href="{% url 'users:register' %}" class="SelfStorage_orange">
                    Зарегистрируйтесь
                </a>
            </span>
        </form>
    </div>
{% endblock %}

{% block footer %}{% endblock %}

templates/my-rent.html
{% extends "base.html" %}
{% load static %}
{% block title %}My Rent{% endblock %}
{% block content %}

{% if user.is_authenticated %}
<main class="container mt-header">
  <div class="row" role="tablist">
    {% include "includes/small-menu.html" %}
    <div class="col-lg-9">
      <div class="card tab-content p-5">
        <h1 class="fw-bold SelfStorage_green mb-3">Добрый день, {{ user.first_name }}!</h1>

        {% if has_expiring %}
        <h4 class="SelfStorage_grey my-3">
          Срок одного или нескольких заказов подходит к концу!<br>
        </h4>
        {% endif %}

        <a href="#" class="SelfStorage_orange mb-5" data-bs-toggle="modal" data-bs-target="#rentModal">История аренды</a>

        <div class="modal fade" id="rentModal" tabindex="-1" aria-labelledby="rentModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="rentModalLabel">История аренды</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
              </div>

              {% if history_orders %}
				  {% for order in history_orders %}
				  <div class="modal-body pe-3 mb-5 pt-2">
					<h4 class="SelfStorage_green">
					  <span class="SelfStorage_gray my_text_size">Склад: </span>
					  <span class="SelfStorage_green my_text_size">{{ order.cell.address.name }}</span>
					</h4>

					<h4>
					  <span class="SelfStorage_gray my_text_size">Адрес: </span>
					  <span class="SelfStorage_green my_text_size">{{ order.cell.address.address }}</span>
					</h4>

					<h4 class="SelfStorage_green">
					  <span class="SelfStorage_gray my_text_size">Размер контейнера: </span>
					  <span class="SelfStorage_green my_text_size">{{ order.cell.cell_size.size }}</span>
					  <span class="SelfStorage_gray my_text_size">м2</span>
					</h4>

					<h4>
					  <span class="SelfStorage_gray my_text_size">№: </span>
					  <span class="SelfStorage_green my_text_size">{{ order.id }}</span>
					</h4>

					<h4 class="SelfStorage_green">
					  <span class="SelfStorage_gray my_text_size">Срок аренды: </span>
					  <span class="SelfStorage_green my_text_size">
						{{ order.start_storage|date:"d.m.Y" }} — {{ order.end_storage|date:"d.m.Y" }}
					  </span>
					</h4>
                    <h4 class="SelfStorage_gray">
                        <span class="SelfStorage_gray my_text_size">Перечень вещей: </span>
					</h4>
                    <h4 class="SelfStorage_green">
                        <span class="SelfStorage_gray my_text_size">{{ order.node }}</span>
                    </h4>
					<a href="#" class="SelfStorage_orange">Нужна помощь?</a>
				  </div>
				  {% endfor %}
              {% else %}
				  <div class="my_box_size">
					<h4 class="SelfStorage_green">
					  <span class="SelfStorage_gray my_text_size">У вас нет истории аренды.</span>
					</h4>
				  </div>
              {% endif %}
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
              </div>
            </div>
          </div>
        </div>

        {% if active_orders %}
			{% for order in active_orders %}
			<div class="mb-5 pt-2">
			  {% if order.days_left != None and order.days_left <= 3 %}
			  <h5 class="SelfStorage_grey my-3">
				Срок аренды подходит к концу. Вы можете продлить аренду или забрать вещи до {{ order.end_storage|date:"d.m.Y" }} включительно.
			  </h5>
			  {% endif %}

			  <h4 class="SelfStorage_green">
				<span class="SelfStorage_gray my_text_size">Склад: </span>
				<span class="SelfStorage_green my_text_size">{{ order.cell.address.name }}</span>
			  </h4>
			  <h4>
				<span class="SelfStorage_gray my_text_size">Адрес: </span>
				<span class="SelfStorage_green my_text_size">{{ order.cell.address.address }}</span>
			  </h4>
			  <h4 class="SelfStorage_green">
				<span class="SelfStorage_gray my_text_size">Размер контейнера: </span>
				<span class="SelfStorage_green my_text_size">{{ order.cell.cell_size.size }}</span>
				<span class="SelfStorage_gray my_text_size">м2</span>
			  </h4>
			  <h4>
				<span class="SelfStorage_gray my_text_size">№: </span>
				<span class="SelfStorage_green my_text_size">{{ order.id }}</span>
			  </h4>
			  <h4 class="SelfStorage_green">
				<span class="SelfStorage_gray my_text_size">Срок аренды: </span>
				<span class="SelfStorage_green my_text_size">{{ order.start_storage|date:"d.m.Y" }} — {{ order.end_storage|date:"d.m.Y" }}</span>
			  </h4>

			  <div class="my_top">
				<form action="{% url 'storage:extend_rent' order.id %}" method="post">
				  {% csrf_token %}
				  <button type="button" class="btn fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_green SelfStorage__btn2_green mb-3" data-bs-toggle="modal" data-bs-target="#extendModal{{ order.id }}">
                      Продлить аренду
                  </button>
				</form>
			  </div>





                <div class="modal fade" id="extendModal{{ order.id }}" tabindex="-1" aria-labelledby="extendModalLabel{{ order.id }}" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <form action="{% url 'storage:extend_rent' order.id %}" method="post">
                        {% csrf_token %}
                        <div class="modal-header">
                          <h5 class="modal-title" id="extendModalLabel{{ order.id }}">Продлить аренду</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                          <label for="days" class="form-label">На сколько дней продлить?</label>
                          <input type="number" name="days" id="days" class="form-control" min="1" max="365" required>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                          <button type="submit" class="btn btn-success">Подтвердить</button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>








			  <div>
				<button type="button" class="btn fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_orange SelfStorage__btn2_orange mb-3" data-bs-toggle="modal" data-bs-target="#boxModal{{ order.id }}">
				  Открыть бокс
				</button>
			  </div>
			  <div class="modal fade" id="boxModal{{ order.id }}" tabindex="-1" aria-labelledby="boxModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-lg">
				  <div class="modal-content">
					<div class="modal-header">
					  <h5 class="modal-title" id="ModalLabel">Перечень вещей</h5>
					  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
					</div>
					<div class="modal-body">
					  <h5 class="SelfStorage_gray">{{ order.node }}</h5>
					</div>
					<div class="modal-footer">
					  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
					</div>
				  </div>
				</div>
			  </div>
			  <a href="#" class="SelfStorage_orange">Нужна помощь?</a>
			</div>
			{% endfor %}
		{% else %}
		<div class="my_box_size">
		  <h4 class="SelfStorage_green">
			<span class="SelfStorage_gray my_text_size">У вас нет активной аренды.</span>
		  </h4>
		</div>
        {% endif %}

      </div>
    </div>
  </div>
</main>
{% else %}
<main class="container mt-header">
  <div class="row top-up butt-up" role="tablist">
    <span class="fs_24">Войдите в учетную запись
      <a class="fs_24 SelfStorage_orange" href="{% url 'users:login' %}">войти</a>, или
      <a class="fs_24 SelfStorage_orange" href="{% url 'users:login' %}">зарегистрируйтесь</a>.
    </span>
  </div>
</main>
{% endif %}
{% endblock %}

templates/order.html
{% extends "base.html" %}
{% load static %}
{% block title %}Арендовать бокс{% endblock %}
{% block content %}

{% if user.is_authenticated %}
    <main class="container mt-header ">
        <div class="row" role="tablist">
            {% include "includes/small-menu.html" %}

            <div class="col-lg-9">
                <div class="card tab-content p-5">
                    <div class="tab-pane fade show active" id="LK" role="tabpanel" aria-labelledby="LK-tab">
                        <h2>Создать заказ</h2>

<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        {{ form.start_storage.label_tag }}<br>
        {{ form.start_storage }}
    </div>
    <div class="mb-3">
        {{ form.end_storage.label_tag }}<br>
        {{ form.end_storage }}
    </div>
    <div class="mb-3">
        {{ form.cell.label_tag }}<br>
        {{ form.cell }}
    </div>
    <div class="mb-3">
        {{ form.promo.label_tag }}<br>
        {{ form.promo }}
    </div>
    <div class="mb-3">
        {{ form.node.label_tag }}<br>
        {{ form.node }}
    </div>
    <button type="submit" class="btn btn-primary">Оформить заказ</button>
</form>

                    </div>
                </div>
            </div>

        </div>
    </main>
{% else %}
    <main class="container mt-header">
        <div class="row top-up butt-up" role="tablist">
            <span class="fs_24 ">Войдите в учетную запись
                <a class="fs_24 SelfStorage_orange" href=
                        "{% url 'users:login' %}">войти</a>,
                 или
                 <a class=" fs_24 SelfStorage_orange" href=
                         "{% url 'users:register' %}">зарегистрируйтесь</a>.
            </span>
        </div>
    </main>
{% endif %}
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}Регистрация{% endblock %}
{% block content %}
    <div class="top-up pt-5 d-flex justify-content-center align-items-center">
        <form method="POST" action="{% url 'users:register' %}" class="d-flex flex-column align-items-center" style="max-width: 420px">
            {% csrf_token %}
        <h1 class="fw-bold mb-3">Регистрация</h1>
        <input type="text" name="{{ form.first_name.name }}" required
               class="form-control border-8 mb-3 py-3 px-5 border-0 fs_20
               SelfStorage__bg_lightgrey"
               placeholder="Имя" value="{{ form.first_name.value|default_if_none:'' }}">
        {{ form.first_name.errors }}
        <input type="text" name="{{ form.last_name.name }}" required
           class="form-control border-8 mb-3 py-3 px-5 border-0 fs_20
           SelfStorage__bg_lightgrey"
           placeholder="Фамилия" value="{{form.last_name.value|default_if_none:'' }}">
        {{ form.last_name.errors }}

        <input type="email" name="{{ form.email.name }}" required
               class="form-control border-8 mb-3 py-3 px-5 border-0 fs_20
               SelfStorage__bg_lightgrey"
               placeholder="E-mail" value="{{ form.email.value|default_if_none:'' }}">
        {{ form.email.errors }}

        <input type="text" name="{{ form.phone.name }}" required
               class="form-control border-8 mb-3 py-3 px-5 border-0 fs_20
               SelfStorage__bg_lightgrey"
               placeholder="Телефон" value="{{ form.phone.value|default_if_none:'' }}">
        {{ form.phone.errors }}

        <input type="text" name="{{ form.address.name }}" required
               class="form-control border-8 mb-3 py-3 px-5 border-0 fs_20
               SelfStorage__bg_lightgrey"
               placeholder="Адрес" value="{{ form.address.value|default_if_none:'' }}">
        {{ form.address.errors }}

        <input type="password" name="{{ form.password1.name }}" required
               class="form-control border-8 mb-3 py-3 px-5 border-0 fs_20
               SelfStorage__bg_lightgrey"
               placeholder="Пароль">
        {{ form.password1.errors }}

        <input type="password" name="{{ form.password2.name }}" required
               class="form-control border-8 mb-3 py-3 px-5 border-0 fs_20
               SelfStorage__bg_lightgrey"
               placeholder="Подтверждение пароля">
        {{ form.password2.errors }}

        <span class="fw-light SelfStorage_grey">Нажимая на кнопку, вы подтверждаете свое <a href="{% static 'Consent to the processing of personal data.pdf' %}" class="SelfStorage_grey">согласие на обработку персональных данных</a></span>

        <button type="submit" class="btn border-8 py-3 px-5 mt-4 mb-2 w-100
        text-white fs_24 SelfStorage__bg_orange SelfStorage__btn2_orange">Зарегистрироваться</button>

        <span>Уже зарегистрированы? <a href="{% url 'users:login' %}" class="SelfStorage_orange">Войти в личный кабинет</a></span>
        </form>
    </div>
{% endblock %}
{% block footer %}{% endblock %}